cxx_binary(
  name = "monster_fbs_test",
  srcs = [
    "MonsterFbsTest.cpp",
  ],
  deps = [
    "//:flatbuffers",
  ],
)

cxx_binary(
  name = "simple_fbs_test",
  srcs = [
    "SimpleFbsTest.cpp",
  ],
  deps = [
    "//:flatbuffers",
  ],
)
