// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SIMPLE_MYFBS_H_
#define FLATBUFFERS_GENERATED_SIMPLE_MYFBS_H_

#include "flatbuffers/flatbuffers.h"

namespace MyFbs {

struct TestStruct;

struct TestTable;
struct TestTableBuilder;
struct TestTableT;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) TestStruct FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t a_;

 public:
  TestStruct() {
    memset(static_cast<void *>(this), 0, sizeof(TestStruct));
  }
  TestStruct(uint16_t _a)
      : a_(flatbuffers::EndianScalar(_a)) {
  }
  uint16_t a() const {
    return flatbuffers::EndianScalar(a_);
  }
};
FLATBUFFERS_STRUCT_END(TestStruct, 2);

struct TestTableT : public flatbuffers::NativeTable {
  typedef TestTable TableType;
  uint16_t a;
  TestTableT()
      : a(0) {
  }
};

struct TestTable FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TestTableT NativeTableType;
  typedef TestTableBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_A = 4
  };
  uint16_t a() const {
    return GetField<uint16_t>(VT_A, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_A) &&
           verifier.EndTable();
  }
  TestTableT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TestTableT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<TestTable> Pack(flatbuffers::FlatBufferBuilder &_fbb, const TestTableT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TestTableBuilder {
  typedef TestTable Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_a(uint16_t a) {
    fbb_.AddElement<uint16_t>(TestTable::VT_A, a, 0);
  }
  explicit TestTableBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  TestTableBuilder &operator=(const TestTableBuilder &);
  flatbuffers::Offset<TestTable> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TestTable>(end);
    return o;
  }
};

inline flatbuffers::Offset<TestTable> CreateTestTable(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t a = 0) {
  TestTableBuilder builder_(_fbb);
  builder_.add_a(a);
  return builder_.Finish();
}

flatbuffers::Offset<TestTable> CreateTestTable(flatbuffers::FlatBufferBuilder &_fbb, const TestTableT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline TestTableT *TestTable::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<MyFbs::TestTableT> _o = std::unique_ptr<MyFbs::TestTableT>(new TestTableT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void TestTable::UnPackTo(TestTableT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = a(); _o->a = _e; }
}

inline flatbuffers::Offset<TestTable> TestTable::Pack(flatbuffers::FlatBufferBuilder &_fbb, const TestTableT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateTestTable(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<TestTable> CreateTestTable(flatbuffers::FlatBufferBuilder &_fbb, const TestTableT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const TestTableT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _a = _o->a;
  return MyFbs::CreateTestTable(
      _fbb,
      _a);
}

}  // namespace MyFbs

#endif  // FLATBUFFERS_GENERATED_SIMPLE_MYFBS_H_
