# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MyFbs

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TestStruct(object):
    __slots__ = ['_tab']

    # TestStruct
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TestStruct
    def FieldA(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # TestStruct
    def FieldB(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(1))

def CreateTestStruct(builder, fieldA, fieldB):
    builder.Prep(1, 2)
    builder.PrependUint8(fieldB)
    builder.PrependUint8(fieldA)
    return builder.Offset()
